### ISSUE TITLE
Project that worked a few days ago not compiling

### ISSUE THREAD

**Issue by JKoltsov** [redivis/help#14]
Hi--I have a transform that just runs and runs and runs and nothing is happening.  Ian, I shared the project with you:  Cervical Outpatient Surgery MEDICARE.  The only changes I made from this same project (the non-medicare version) that I ran a few days ago was switching to the medicare datasets, and then putting all of dx1-dx4 on the left side of the logical equation, since that is allowed now.  I have two issues:
1)  Transform "Flag exlusions 1" is not running now--just spinning.  I tried cancelling and restarting, but now when I push run again the button says cancelling and just spins.
2) The step after that is now giving me the error flag "The query is too large. The maximum query length is 256.000K characters, including comments and white space characters."  I do have a long list of codes, but I used this exact same query in my non-medicare project and it ran fine, so not sure why now I am over the limit.

**Comment by imathews** [comment]
@JKoltsov Just took a look at your project — it appears that issue (1) has been resolved? It seems like the transform completed, though not sure why it was stuck... In certain rare cases, you may need to do a full reload of the page to see that the run has completed.

For (2), this is a known issue, which you can track at https://github.com/redivis/meta/issues/125 for its resolution. I'm not sure why this would fail when it previously succeeded, though it could be that the query layout changed when adding dx1-4 to the left input in such a way as to push this over the top.  You might find the like / not like operators (https://help.redivis.com/for-researchers/working-with-data/concepts/comparisons) useful as a substitute for exceptionally long lists

**Comment by JKoltsov** [comment]
There is still something funky going on with the run button--this time even though it was running, it didn't switch to show the spinning cancel button until I reloaded the page.

For #2--I was over the limit both ways--both as I originally had it with each dx on 1 line, and with the new version with all dx's on one line, so doesn't seem like that was what pushed it over the top.  I split it into two steps for now to run...

**Comment by JKoltsov** [comment]
Now, I cancelled that run because it was taking a really long time.  Clicked run to start again, now the button is spinning and saying "cancelling"...  I clicked refresh and it changed to spinning and "cancel" as it should be.

**Comment by imathews** [comment]
Thanks @JKoltsov — we'll look into this

**Comment by JKoltsov** [comment]
Hmmm...still taking a really long time to run--been going for over 3 minutes now.  This is the "Flag exclusions 2" on the Cervical Outpatient Surgery MEDICARE project.

**Comment by JKoltsov** [comment]
Okay, the Flag exclusions 1 and flag exclusions 2 nodes both ran now--though they seemed to take way longer than they used to (>10 minutes...usually compiled in 1-2). However, now I got to the flax exclusions 3 node, and I am getting the following error:
Syntax error: Expected ")" but got keyword EXCLUDE at [4:12]

The goal of the node was to 1) create a variable exclude3 to track the exclusions for dx3 and dx4 (that did not fit on the previous node), 2) create a variable exclusions that was true if any of exclude1 exclude2 or exclude3 were true, and then 3) aggregate the dataset, creating two variables:  one that is true if any services for that enrolid on that particular SVC date met the criteria of being a cervical surgery, and one variable that is true if any of the outpatient records for that enrolid, svcdate trigger an exclusion critera. 

Not sure where the ")" the error is referring to is happening--these pieces of code were used previously and compiled earlier this week, the only change is that I split the exclusions into 2 steps so now have 3 exclude variables to check rather than 2...shouldn't have changed anything.

**Comment by imathews** [comment]
@JKoltsov thanks for this info, it's quite helpful in getting to the root of things. It sounds like a few things are going on here:
1. The queries are taking a long time to run because the size of your intermediary tables is quite large, meaning that the querying engine has to write over 1B records as the output of the first step before executing the second. As a general rule, the performance of queries on Redivis is largely dependent on the size of the output table, not necessarily the input table (selecting 1000 records from 1B is much faster than selecting 1M records from 1M). I imagine you were previously able to do the filtering in one step, so that likely 
2. However, there does seem to be a bug w/ cancelling run jobs; we'll work on a fix
3. EXCLUDE is a reserved keyword in SQL, and your variable named "exclude" is then creating this syntax error behind the scenes. This is actually a bug on our end, but the temporary workaround would be to name the variable something else (even `EXCLUDED` should be fine).

Finally, all of this pain is being caused by having to split up the query because of the long list. We have a solution in the works here which should make it practically impossible to hit this query size limit, removing many of the problems you're facing. We hope to have fixes for this out as early as EOD Monday, but because of some upcoming travel and obligations on the team this may take until Wednesday.

**Comment by JKoltsov** [comment]
Thanks, Ian:
1) Yes, was much nicer when I could do this all in one step--however, for some reason, even though it is a large table, it didn't seem to take this long before...
2) sounds good
3) Ah...good to know.  Will change the variable name and retry.

**Comment by imathews** [comment]
@JKoltsov We've just released an update that parameterizes lists in such a way that you should run into these issues when using long lists — you should now be able to do all of this in one transform!

Thanks for the patience and the debugging help. 

ps - We haven't had the opportunity to fully dive into the weird cancelling behavior, but it's on our radar and will be resolved shortly.

**Comment by JKoltsov** [comment]
Awesome!  Thanks!
